#!/bin/bash
# vim: set ft=sh

set -e -x

ROOT=$PWD

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd $GOPATH/src/github.com/concourse/archive-resource

make

cd ..
cp -a archive-resource $ROOT/build-root
