#!/bin/bash
# vim: set ft=sh

set -e -x

ROOT=$PWD

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

BUILD_DIR=$PWD/built-resource

cd $GOPATH/src/github.com/concourse/archive-resource

make

cp -a assets/ Dockerfile $BUILD_DIR
