#!/bin/bash
# vim: set ft=sh

export GOPATH=/tmp/gopath
export PATH=$GOPATH/bin:$PATH
export REPO_DIR=$GOPATH/src/github.com/concourse/archive-resource

mkdir -p $(dirname $REPO_DIR)
ln -s $PWD $REPO_DIR

cd $REPO_DIR

make
